Update deploy.yml

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -1,18 +1,16 @@
 name: Deployment Pipeline
-
 on:
   push:
     branches: [ "development", "stage", "test" ]
-
 env:
   PROJECT_TYPE: 'laravel'
-
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
       - name: Deployment
         id: sonar
+        if: github.ref_name == 'development' || github.ref_name == 'stage' || github.ref_name == 'test'
         uses: appleboy/ssh-action@master
         with:
           host: ${{ secrets.REMOTE_HOST }}
@@ -22,58 +20,65 @@ jobs:
           script: |
             set -e
             BRANCH=${{ github.ref_name }}
+          
+            TEST_BRANCH="test"
+            TEST_PROJECT_KEY="${PROJECT_TYPE}-project-${TEST_BRANCH}"
+            # 1. INITIALIZATION (always use TEST)
+            cd /var/www/html/$TEST_BRANCH/$PROJECT_TYPE-project
+            git pull origin $TEST_BRANCH
             
-            # 1. INITIALIZATION
-            cd /var/www/html/$BRANCH/$PROJECT_TYPE-project
-            git pull origin $BRANCH
-
-            # 2. SONARQUBE ANALYSIS
+            # 2. SONARQUBE ANALYSIS (always run on TEST)
             export SONAR_NODE_ARGS='--max-old-space-size=512'
             /home/ubuntu/sonar-scanner/bin/sonar-scanner \
-              -Dsonar.projectKey=${PROJECT_TYPE}-project \
+              -Dsonar.projectKey=$TEST_PROJECT_KEY \
               -Dsonar.sources=app \
               -Dsonar.inclusions=**/*.php \
               -Dsonar.host.url=${{ secrets.SONAR_HOST_URL }} \
               -Dsonar.login=${{ secrets.SONAR_TOKEN }}
+            # 3. QUALITY GATE CHECK (always check TEST)
+            STATUS="PENDING"
 
-            # 3. QUALITY GATE CHECK
-            sleep 10
+            
             for i in {1..24}; do
-              STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=${PROJECT_TYPE}-project" | jq -r '.projectStatus.status')
+              STATUS=$(curl -s -u ${{ secrets.SONAR_TOKEN }}: "${{ secrets.SONAR_HOST_URL }}/api/qualitygates/project_status?projectKey=$TEST_PROJECT_KEY" | jq -r '.projectStatus.status')
               if [ "$STATUS" = "OK" ] || [ "$STATUS" = "ERROR" ]; then break; fi
               sleep 2
             done
+            echo "Scan Result (Test): $STATUS"
 
-            if [ "$STATUS" != "OK" ]; then 
-              exit 1 
+            
+            if [ "$STATUS" != "OK" ]; then
+              echo "Note: Deployment FAILED because Test branch Quality Gate NOT PASSED."
+              echo "::error title=Quality Gate Failed::Project: $PROJECT_TYPE | Current Branch: $BRANCH | Scan Result (Test): $STATUS | Deployment FAILED because Test branch Quality Gate NOT PASSED."
+              exit 1
             fi
-            sleep 5
+
             
             # 4. PROJECT SPECIFIC BUILD
             case "$PROJECT_TYPE" in
-                vue) 
-                  VITE_BASE_URL="/$PROJECT_TYPE/$BRANCH/" 
-                  npm run build 
+                vue)
+                  VITE_BASE_URL="/$PROJECT_TYPE/$BRANCH/"
+                  npm run build
                   ;;
-                nextjs) 
-                  npm run build 
-                  pm2 restart $PROJECT_TYPE-$BRANCH 
+                nextjs)
+                  npm run build
+                  pm2 restart $PROJECT_TYPE-$BRANCH
                   ;;
-                laravel) 
+                laravel)
                   sudo php artisan optimize
                   ;;
             esac
-
-      - name: Notify
-        if: always()
-        run: |
-          STATUS="${{ job.status == 'success' && 'SUCCESS' || 'FAILED' }}"
-          if [[ "${{ job.status }}" == "success" ]]; then
-            MSG="Deployment successful! "
-          else
-            [[ "${{ steps.sonar.outcome }}" == "failure" ]] && ERR="Quality Gate" || ERR="Build/Deploy"
-            MSG="Failed at: $ERR step "
-          fi
-          curl -X POST -H 'Content-type: application/json' \
-          --data "{\"text\":\"*[$STATUS]* \n*Project:* ${{ env.PROJECT_TYPE }} \n*Branch:* ${{ github.ref_name }} \n*Status:* $MSG\"}" \
-          "${{ secrets.SLACK_WEBHOOK }}"
+            
+      # - name: Notify
+      #   if: always()
+      #   run: |
+      #     STATUS="${{ job.status == 'success' && 'SUCCESS' || 'FAILED' }}"
+      #     if [[ "${{ job.status }}" == "success" ]]; then
+      #       MSG="Deployment successful! "
+      #     else
+      #       [[ "${{ steps.sonar.outcome }}" == "failure" ]] && ERR="Quality Gate" || ERR="Build/Deploy"
+      #       MSG="Failed at: $ERR step "
+      #     fi
+      #     curl -X POST -H 'Content-type: application/json' \
+      #     --data "{\"text\":\"*[$STATUS]* \n*Project:* ${{ env.PROJECT_TYPE }} \n*Branch:* ${{ github.ref_name }} \n*Status:* $MSG\"}" \
+      #     "${{ secrets.SLACK_WEBHOOK }}"
